default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_pessoal_development
  username: lucascyrne # substitua pelo seu nome de usuário local do PostgreSQL
  password: sing lots time # substitua pela sua senha local do PostgreSQL
  host: localhost

test:
  <<: *default
  database: blog_pessoal_test
  username: lucascyrne # substitua pelo seu nome de usuário local do PostgreSQL
  password: sing lots time # substitua pela sua senha local do PostgreSQL
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
